### PR TITLE
Automated update to image-utils

### PR DESCRIPTION
**Pull request by seamusdemora**
Hello @scruss , I've forked the repo you created, and written a small `bash` script to update my fork with updates that RonR posts in the RPi forum thread he started. This pull request is just to bring your repo up-to-date with mine. 

And yes - I read your disclaimer in the README file you created. I understand completely if you don't wish to be bothered with this. Please **let me know** if that's the case, and I'll "branch off" - or whatever it is when there's a bifurcation/schism/whatever.

### CODE REVIEW

**Comment by scruss** [comment]
Hi - glad you weren't put off by the "please go away" language in the readme. If you've found a way to automatically update this, that's entirely cool. You're welcome to the repo; now, if only I knew of a way to make yours master while still redirecting through here for the folks who know about mine …

**Comment by seamusdemora** [comment]
There's probably a way to do that, but I don't know how. Since yours is the "original", I'm thinking you'll be the one that has to make the change. 

Best outcome of all of this would be that RonR assumed a role in this. I certainly don't mind maintaining this & handling the admin side, but it's occurred to me this could "blow up" someday. I've had to make some assumptions about how raspberrypi.org website manages their stable of downloadable files. It's always better to "know" than assume & RonR's support could eliminate the uncertainty.

**Comment by seamusdemora** [comment]
Hello again, scruss,

Since sending you an email a few minutes ago, I've found I can still add comments against the first pull request (git can be quite confusing at times imo). Anyway - covered it all in the email I think, but if you wanna merge this pull request, then we'll go from there.

**Comment by martignoni** [comment]
Is there any timeframe for the merge of this PR?

**Comment by scruss** [comment]
nope

**Comment by seamusdemora** [comment]
Hmmm... don't understand the "Pull request closed" note above. However, when I click the link, or the `Fork settings` button, I get this ominous warning: 

Screen Shot 2020-06-16 at 3 30 16 PM

**Pull request closed without merging**
